[template]
prefix = "beacon/registry/default"
keys = [
  "/http",
  "/tcp"
]

owner = "root"
mode = "0644"
src = "haproxy.cfg.tmpl"
#dest = "/etc/haproxy/haproxy.cfg"
dest = "/tmp/haproxy.cfg"

#check_cmd = "/usr/sbin/haproxy -c -f {{ .src }}"
#reload_cmd = "/etc/init.d/haproxy reload"